Feature/iss11 signup login integration
deep-diver/portfolio_template pull request #15
Opened 2017-03-29 03:48 UTC by taegyun0922

2017-03-29 04:20 UTC, deep-diver requested changes
@taegyun0922 체크

2017-03-29 04:20 UTC, deep-diver commented on src/main/resources/templates/signup.html
> +            <form id = 'content'>
change single quote to double quote

' (단일 따옴표) 를 " (쌍 따옴표)로 변경.
HTML 문서 전반에 일관성 유지

2017-03-29 04:20 UTC, deep-diver commented on src/main/resources/templates/signup.html
> +            <div id = 'box'>
id "box" looks very general, but it seem to be a specific area (for selection)
- consider to remove the div or rename it to something else

box 라는 아이디는 너무 일반적인 이름인데, 사용되는 곳은 여기 한곳 뿐인것 같음.
딱히 box라는 div가 필요 없을지도 모르겠음. 삭제하던지, 다른 이름으로 변경하면 어떨지?
(또는 login.html 처럼 아이디를 삭제?)

2017-03-29 04:20 UTC, deep-diver commented on src/main/resources/templates/signup.html
> +                  <input type="submit" value="submit" >
consider to change input tag to button tag.

login.html과 비슷한 컴포넌트 형태로 변경 필요 검토
input 태그를 button 태그로? (일관성 유지)

2017-03-29 04:21 UTC, deep-diver approved these changes

2017-03-30 10:41 UTC, taegyun0922 commented
#11 fixed

2017-03-30 10:43 UTC, merged